name: events_map
description: "Aplicación Flutter de eventos en Google Maps con panel de controles y gestión de marcadores."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Google Maps
  google_maps_flutter: ^2.5.0

  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.8

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  # Haptic Feedback
  vibration: ^3.1.3

  # File operations
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
